Good paterns13.2
nyuqiu/tomasz-orzol-kodilla-java pull request #7
Opened 2019-01-12 15:47 UTC by nyuqiu

2019-01-12 18:07 UTC, lukaszbarc requested changes

2019-01-12 18:07 UTC, lukaszbarc commented on kodilla-good-paterns/src/main/java/com/kodilla/good/paterns/challenges/ProductOrderService/BuyingDto.java
> +    private boolean isBought;
bez is

2019-01-12 18:07 UTC, lukaszbarc commented on kodilla-good-paterns/src/main/java/com/kodilla/good/paterns/challenges/ProductOrderService/BuyingRepository.java
> +    boolean createOrder(User user, String product, String address);
BuyingRequest

2019-01-12 18:07 UTC, lukaszbarc commented on kodilla-good-paterns/src/main/java/com/kodilla/good/paterns/challenges/ProductOrderService/BuyingService.java
> +    boolean buy(User user, String product, String address);
BuingRequest?

2019-01-12 18:07 UTC, lukaszbarc commented on kodilla-good-paterns/src/main/java/com/kodilla/good/paterns/challenges/ProductOrderService/EmailService.java
> +        System.out.println("Order has been created for "+user.getName()+user.getSurname());
spacja

2019-01-13 00:12 UTC, nyuqiu reviewed
Poprawione

2019-01-20 17:32 UTC, merged